def even_generator(limit):
    for i in range(2, limit + 1, 2):
        yield i



for num in even_generator(10):
    print(num)

# def even_generator(limit):: This line defines a generator function named even_generator that takes one argument, limit, 
# which specifies the upper limit of even numbers to generate.
# for i in range(2, limit + 1, 2):: This line starts a loop using the range function. 
# It iterates over even numbers starting from 2 up to the specified limit (inclusive) with a step of 2. 
# This ensures that only even numbers are generated.
# yield i: Inside the loop, this line yields (produces) the current even number i from the generator function. 
# The function temporarily suspends its execution and returns the value of i to the caller. When the function is called again, 
# it resumes execution from where it left off.
# for num in even_generator(10):: This line iterates over the values generated by calling the even_generator function with a limit of 10.
#  It retrieves each generated even number and assigns it to the variable num.
# print(num): Inside the loop, this line prints each even number num that is generated by the even_generator function.
# When you run this code, it will print all even numbers from 2 to 10 (inclusive) because limit is set to 10. 
# The generator function generates each even number on-demand as it is iterated over in the for loop, 
# which is memory-efficient compared to generating and storing all even numbers in a list upfront.







